#!/usr/bin/env python3
"""One-time script to categorize domains from kvas_list into thematic files."""

import re
from pathlib import Path
from collections import defaultdict

CATEGORIES = {
    "social": {
        "description": "Social networks, messengers",
        "patterns": [
            # Telegram
            r"telegram", r"t\.me$", r"tx\.me$", r"tg\.dev$", r"telega\.one$", r"telegra\.ph$",
            r"telesco\.pe$", r"cdn-telegram", r"comments\.app$", r"contest\.com$", r"fragment\.com$",
            # Discord
            r"discord", r"dis\.gd$",
            # Facebook / Meta
            r"facebook", r"fb\.com$", r"fbcdn", r"fbsbx", r"internalfb", r"meta\.com$",
            r"instagram", r"cdninstagram", r"ig\.me$", r"threads\.net$",
            # Twitter / X
            r"twitter", r"x\.com$", r"x\.ai$", r"t\.co$", r"tweetdeck", r"twimg",
            r"twitpic", r"twtrdns", r"twttr", r"twvid", r"cms-twdigitalassets",
            r"ads-twitter", r"periscope\.tv$", r"pscp\.tv$",
            # LinkedIn
            r"linkedin", r"licdn\.com$",
            # Messengers
            r"viber\.com$", r"signal\.org$", r"simplex\.", r"threema",
            # Other social
            r"guilded\.gg$", r"reddit", r"quora\.com", r"mastodon",
            r"vine\.co$", r"linktr\.ee$", r"mssg\.me$",
        ],
    },
    "video": {
        "description": "Video streaming, YouTube, Netflix, TikTok, anime",
        "patterns": [
            # YouTube
            r"youtube", r"youtu\.be$", r"googlevideo", r"ytimg", r"yt-video",
            r"yting\.com$", r"wide-youtube",
            # Netflix
            r"netflix", r"nflx",
            # TikTok
            r"tiktok", r"ttwstatic", r"byteoversea", r"muscdn", r"musical\.ly$",
            r"ibytedtos", r"capcut",
            # Anime
            r"anilibria", r"animaunt", r"anime-portal", r"animebest", r"animedia",
            r"animego", r"animespirit", r"anistar", r"anistars", r"anidub",
            r"sovetromantica", r"yummyani", r"shiza-project", r"jut-su", r"jut\.su$",
            r"shikimori", r"mangadex", r"mangahub", r"mangapark",
            # Streaming / TV
            r"crunchyroll", r"primevideo", r"deezer\.com$", r"tidal\.com$",
            r"spotify\.com$", r"soundcloud", r"mixcloud",
            r"kino\.pub$", r"kinopub", r"kinogo", r"kinovod", r"kinozal",
            r"hdrezka", r"hd-rezka", r"rezka\.", r"rezkify", r"voidboost",
            r"lostfilm", r"newstudio", r"coldfilm", r"seasonvar",
            r"hdkinoteatr", r"filmix", r"filmitorrent", r"fast-torrent",
            r"dorama", r"doramy", r"mydoramy",
            r"ilook\.tv$", r"iptv\.online$", r"livetv\.sx$",
            r"zetfix", r"zetflix", r"uniongang", r"amedia\.site$",
            r"adultmult\.tv$", r"pimpletv",
            r"7tv\.", r"m3u\.in$", r"onlineradiobox",
            r"widgetapp\.stream$", r"tvfreedom",
            r"api\.service-kp", r"service-kp", r"kpapp\.link$",
            r"kinokopilka", r"kinobase",
            r"bcbits\.com$",  # Bandcamp CDN
        ],
    },
    "ai": {
        "description": "AI services and platforms",
        "patterns": [
            r"openai\.com$", r"oaistatic", r"oaiusercontent", r"chatgpt\.com$",
            r"chat\.com$", r"chat\.openai",
            r"anthropic\.com$", r"claude\.ai$",
            r"groq\.com$", r"grok\.com$",
            r"bard\.google", r"gemini\.google",
            r"generativelanguage\.googleapis",
            r"elevenlabs\.io$", r"recraft\.ai$", r"reve\.art$",
            r"blinkshot\.io$", r"sora\.com$", r"manus\.im$",
            r"copilot\.microsoft", r"designer\.microsoft",
            r"api\.jetbrains\.ai$", r"grazie\.ai$",
            r"codeium\.com$", r"openrouter\.ai$",
            r"lightning\.ai$",
        ],
    },
    "dev": {
        "description": "Developer tools, IDEs, code hosting, CI/CD",
        "patterns": [
            r"jetbrains\.com$", r"jetbrains\.space$", r"myjetbrains", r"intellij\.net$",
            r"gitlab\.com$", r"gitlab\.io$",
            r"bitbucket\.org$",
            r"grafana\.com$",
            r"hashicorp\.com$", r"terraform\.io$", r"vagrantcloud",
            r"mongodb\.com$", r"mongodb\.org$", r"redis\.com$", r"redis\.io$",
            r"neo4j\.com$", r"elastic\.co$",
            r"swagger\.io$", r"buf\.build$",
            r"sentry\.io$", r"snyk\.io$",
            r"ngrok\.com$",
            r"linear\.app$", r"clickup\.com$", r"lucid\.app$", r"hackmd\.io$",
            r"netlify\.com$", r"pages\.dev$", r"herokucdn", r"assets\.heroku",
            r"framer\.com$",
            r"graylog\.org$", r"spacelift\.io$",
            r"docs\.liquibase", r"liquibase\.com$",
            r"cucumber\.io$",
            r"refactoring\.guru$",
            r"hackernoon\.com$", r"indiehackers",
            r"habr\.com$", r"medium\.com$",
            r"leafletjs\.com$", r"reactflow\.dev$",
            r"graph\.org$",
            r"resp\.app$",
            r"openwrt\.org$",
            r"notepad-plus-plus",
            r"bell-sw\.com$",  # BellSoft (Liberica JDK)
            r"bitnami\.com$",
            r"helm\.goharbor\.io$",
            r"prowlarr\.com$", r"radarr\.video$", r"lidarr\.audio$", r"servarr\.com$",
        ],
    },
    "news": {
        "description": "News, media, journalism",
        "patterns": [
            r"bbc\.co", r"bbc\.com$", r"bbci\.co",
            r"dw\.com$", r"euronews", r"foxnews", r"fncstatic",
            r"meduza\.io$", r"novayagazeta", r"novaya\.no$",
            r"thebell\.io$", r"theins\.", r"holod\.media$",
            r"mediazona", r"zona\.media$",
            r"republic\.ru$", r"paperpaper",
            r"proekt\.media$", r"posle\.media$",
            r"verstka\.media$", r"metla\.press$",
            r"spektr\.press$", r"cherta\.media$",
            r"currenttime\.tv$", r"svoboda\.org$", r"rferl\.org$",
            r"radiosvoboda", r"golosameriki", r"kavkaz", r"kavkazr",
            r"sibreal", r"severreal", r"idelreal", r"krymr",
            r"azattyq", r"azathabar", r"ozodi\.org$",
            r"echofm\.online$", r"radiosakharov",
            r"tvrain", r"doxa\.team$", r"doxajournal",
            r"colta\.ru$", r"newtimes\.ru$", r"the-village",
            r"wonderzine", r"exler\.ru$", r"itsmycity",
            r"moscowtimes", r"newsru",
            r"ovd\.", r"ovdinfo", r"memohrc", r"roskomsvoboda",
            r"bellingcat", r"wilsoncenter", r"carnegieendowment",
            r"important-stories", r"istories\.media$",
            r"rsf\.org$", r"hrw\.org$",
            r"strana\.", r"gordonua", r"hromadske", r"obozrevatel",
            r"interfax\.com\.ua", r"rbc\.ua$", r"unian",
            r"korrespondent", r"pravda\.com",
            r"suspilne\.media$", r"ukr\.net$", r"ukr\.radio$",
            r"delfi\.", r"err\.ee$", r"r4\.err", r"postimees",
            r"hs\.fi$", r"is\.fi$", r"yle\.fi$",
            r"politico\.eu$", r"politiken\.dk$", r"welt\.de$",
            r"swissinfo\.ch$", r"telegraph\.co",
            r"baikal-journal", r"fn-volga", r"sakh\.com",
            r"tayga\.info$", r"vesma\.", r"novaline\.fm$",
            r"kovcheg\.live$", r"dovod\.online$",
            r"rezonans\.media$", r"realist\.online$",
            r"skat\.media$", r"agents\.media$", r"arbat\.media$",
            r"germania\.one$", r"usa\.one$",
            r"kasparov\.ru$", r"navalny\.com$",
            r"polit\.ru$", r"ej\.ru$", r"grani\.ru$",
            r"cub\.red$", r"sputnikipogrom",
            r"freemedia\.io$", r"openmedia\.io$",
            r"botnadzor", r"censortracker", r"dpidetector",
            r"rublacklist", r"ntc\.party$",
            r"tjournal\.ru$", r"discours\.io$",
            r"prosleduetmedia", r"provereno\.media$",
            r"thetruestory", r"vot-tak\.tv$",
            r"voynaplemyon", r"freedomletters",
            r"nasvsehtoshnit", r"gulagu\.net$",
            r"slavicsac", r"fonge\.org$", r"fortanga",
            r"ekhokavkaza", r"svtv\.org$",
            r"cyxymu\.info$", r"baginya\.org$",
            r"sebeanus", r"riperam\.org$",
            r"ozi-ru\.org$", r"agentura\.ru$",
            r"4freerussia",
            r"kolsar\.org$", r"semnasem\.org$",
            r"sakharovfoundation", r"ehorussia",
            r"te-st\.org$", r"oi\.legal$",
            r"ohmyswift\.ru$",
            r"news\.google",
            r"flipboard\.com$",
            r"stulchik\.net$", r"sobesednik",
            r"gagadget\.com$", r"root-nation",
            r"activatica\.org$",
            r"mignews\.com$", r"newsroom\.porsche",
            r"vesty\.co\.il$", r"cursorinfo\.co\.il$",
            r"zahav\.ru$", r"9tv\.co\.il$",
            r"locals\.md$", r"telegraf\.",
            r"knowyourmeme", r"kym-cdn",
            r"halooglasi\.com$",
            r"kaktus\.media$", r"knews\.kg$", r"24\.kg$",
            r"nibiru", r"graty\.me$",
        ],
    },
    "torrents": {
        "description": "Torrent trackers and related",
        "patterns": [
            r"rutracker", r"rutor\.", r"nnmclub", r"nnmstatic",
            r"thepiratebay", r"1337x\.to$", r"torrentgalaxy",
            r"piratbit", r"torrent\.by$", r"torrenteditor",
            r"opentrackr", r"tracker\.wf$",
            r"rustorka", r"t-ru\.org$",
            r"booktracker\.org$", r"twirpx",
            r"libgen\.", r"sci-hub", r"flibusta",
            r"annas-archive",
            r"btdig\.com$",
            r"epidemz", r"selezen\.org$",
            r"gamesrepack",
            r"turbobit\.net$", r"zbigz\.com$",
            r"megapeer",
        ],
    },
    "gaming": {
        "description": "Gaming platforms and games",
        "patterns": [
            r"steam", r"valvesoftware",
            r"boosteroid", r"geforcenow", r"gfn\.am$",
            r"supercell", r"clashofclans", r"clashroyale", r"brawlstars",
            r"squadbusters", r"hayday",
            r"gameloft", r"shop\.gameloft",
            r"gamedistribution",
            r"chess\.com$",
            r"f1\.com$", r"formula1",
            r"nba\.com$", r"nfl\.com$", r"nhl\.com$",
            r"premierleague", r"footballapi\.pulselive", r"pulselive\.com$",
            r"strava\.com$",
            r"builds\.parsec", r"public\.parsec",
            r"stalker2",
            r"velocidrone",
            r"f95-?zone", r"attachments\.f95zone",
            r"cdromance",
            r"ghostrc\.game",
            r"itch\.io$",
        ],
    },
    "adult": {
        "description": "NSFW / adult content",
        "patterns": [
            r"pornhub", r"phncdn",
            r"xhamster", r"xhamsterlive",
            r"xvideos", r"xv-ru",
            r"xnxx",
            r"redtube",
            r"chaturbate",
            r"hqporner",
            r"redgifs",
            r"rule34",
            r"gelbooru",
            r"e621\.net$",
            r"hentai-foundry",
            r"nhentai",
            r"danbooru",r"donmai\.us$",
            r"multporn",
            r"pornolab",
            r"playboy\.com$",
            r"coomer\.su$", r"kemono",
            r"vipergirls",
            r"island-of-pleasure",
            r"reddxxx",
            r"yaoilib", r"slashlib",
            r"dobrochan", r"iichan",
        ],
    },
    "vpn-privacy": {
        "description": "VPN services, privacy tools, proxies",
        "patterns": [
            r"nordvpn", r"surfshark", r"mullvad", r"cyberghostvpn",
            r"proton\.me$", r"protonmail", r"protonvpn",
            r"psiphon", r"torproject",
            r"amnezia\.org$",
            r"vpngate", r"vpngen", r"vpnlove", r"vpnpay", r"prostovpn",
            r"redshieldvpn",
            r"startpage\.com$",
            r"dnsleaktest", r"browserleaks",
            r"ifconfig\.me$", r"showip\.net$", r"myip",
            r"10minutemail", r"tempmail", r"cock\.li$",
            r"tuta\.com$", r"tuta\.io$", r"tutanota",
            r"mailfence", r"mailo\.com$", r"zohomail",
            r"simplix\.info$", r"getoutline",
            r"pkgs\.tailscale",
            r"mail-api\.proton",
        ],
    },
    "shopping": {
        "description": "E-commerce, shopping, marketplaces",
        "patterns": [
            r"amazon\.com$", r"gaming\.amazon", r"amazonaws\.com$",
            r"etsy\.com$", r"temu\.com$",
            r"bestbuy\.com$", r"walmart\.com$",
            r"groupon\.com$",
            r"iherb\.com$",
            r"nike\.com$", r"adidas\.com$",
            r"abercrombie", r"hollisterco", r"timberland",
            r"sephora\.com$",
            r"hotels\.com$", r"skyscanner",
            r"olx\.ua$", r"kupujemprodajem",
            r"monoprice",
            r"alza\.hu$", r"allegro\.pl$",
            r"goodreads\.com$", r"gr-assets",
            r"depositphotos", r"freeimages", r"pexels",
            r"patreon\.com$",
            r"buymeacoffee",
            r"gofundme",
            r"bosch-home", r"home-connect",
            r"ducati\.com$", r"porsche\.com$",
            r"volkswagen",
            r"upwork\.com$",
            r"bumble\.com$",
            r"myheritage\.com$",
            r"everand\.com$",
            r"wetransfer\.com$",
        ],
    },
    "crypto": {
        "description": "Cryptocurrency exchanges and services",
        "patterns": [
            r"bitcoin\.org$", r"localbitcoins",
            r"bybit\.com$", r"okx\.com$",
            r"coingate", r"coinpayments", r"coinsbee",
            r"bestchange", r"bitrefill",
            r"cloudex\.cc$", r"cbilling",
            r"polymarket", r"opensea\.io$",
            r"oasis\.app$", r"paraswap",
            r"forklog\.com$",
        ],
    },
    "cloud-infra": {
        "description": "Cloud, hosting, enterprise IT, hardware vendors",
        "patterns": [
            r"digitalocean", r"hetzner", r"contabo", r"ionos",
            r"hostinger", r"hostgator", r"bluehost", r"dreamhost",
            r"godaddy", r"networksolutions", r"webnames",
            r"kamatera", r"lambdalabs",
            r"oracle\.com$", r"ibm\.com$", r"sap\.com$",
            r"microsoft\.com$", r"microsoft365", r"live\.com$", r"live\.net$",
            r"ntp\.msn", r"bing\.com$",
            r"nvidia\.com$", r"developer\.nvidia", r"install\.launcher\.omniverse",
            r"amd\.com$", r"intel\.com$", r"intel\.de$", r"intel\.nl$",
            r"qualcomm", r"broadcom", r"nxp\.com$", r"ti\.com$",
            r"infineon", r"microchip", r"analog\.com$", r"tsmc",
            r"dell\.com$", r"dellcdn", r"lenovo\.com$",
            r"cisco\.com$", r"meraki", r"ubnt\.com$",
            r"vmware\.com$", r"omnissa", r"citrix",
            r"veeam\.com$", r"veritas\.com$",
            r"autodesk\.com$", r"adobe\.", r"canva\.",
            r"atlassian", r"salesforce", r"sfdcopens", r"force\.com$",
            r"force-user-content", r"trailblazer", r"trailhead", r"tellapart",
            r"tableau\.com$",
            r"intuit\.com$", r"intuitibits",
            r"teamviewer",
            r"jamf\.com$",
            r"wpengine",
            r"fastly\.net$", r"b-cdn\.net$", r"akamaihd", r"cdnbunny",
            r"lamcdn\.net$",
            r"cloudflare", r"api\.cloudflare",
            r"appspot\.com$", r"usercontent\.dev$",
            r"google\.dev$", r"lookerstudio\.google",
            r"proactivebackend-pa\.googleapis",
            r"jnn-pa\.googleapis",
            r"suggestqueries\.google",
            r"geolocation\.onetrust", r"onetrust\.com$",
            r"clarity\.ms$",
            r"on24\.com$",
            r"surveymonkey", r"research\.net$",
            r"xerox", r"bradyid", r"flir\.", r"flukenetworks", r"fluke\.com$",
            r"leica-geosystems", r"keysight",
            r"cambiumnetworks", r"ruckuswireless", r"watchguard",
            r"solarwinds", r"trellix", r"avira", r"bitdefender",
            r"malwarebytes", r"clamav", r"pandasecurity",
            r"snort\.org$", r"talosintelligence",
            r"sophos", r"community\.sophos", r"intelix\.sophos",
            r"certifytheweb", r"zerossl", r"letsencrypt",
            r"singlekey-id",
            r"pingdom\.com$", r"zendesk\.com$",
            r"zapier\.com$",
            r"onshape\.com$", r"sketchup\.com$",
            r"chaos\.com$",
            r"spitfireaudio",
            r"as6723\.net$", r"bgpmon",
            r"xtracloud",
            r"quickconnect",
            r"synoforum",
            r"amazon", # catch remaining amazonaws etc
            r"paypal\.com$",
            r"kmail-lists",
            r"apple",
            r"amx\.com$",  # AMX (Harman)
            r"jabra\.com$",
            r"amazfitwatchfaces",
            r"glpals\.com$", r"gpsonextra",
            r"nfl\.com$",
            r"weather\.com$", r"wunderground", r"windguru",
            r"typing\.com$",
            r"nih\.gov$", r"medicalnewstoday",
            r"credly\.com$",
            r"flourish\.studio$",
            r"coursera\.org$",
            r"slideshare",
            r"grammarly\.com$",
            r"notion\.", r"notion-static",
            r"aol\.com$",
            r"fast\.com$",
            r"com\.cdn\.cloudflare",
        ],
    },
    "linux": {
        "description": "Linux distros, package repos, open-source infra",
        "patterns": [
            r"cachyos\.org$", r"nobaraproject", r"linuxtracker",
            r"pypi\.org$", r"files\.pythonhosted",
            r"factory\.talos\.dev$",
            r"openwrt\.org$", r"omv-extras",
            r"vyos\.io$",
            r"linuxiac",
            r"rpm\.pika-os",
            r"postfix\.org$",
            r"gnome-look\.org$",
            r"daemon-tools",
        ],
    },
    "forums-books": {
        "description": "Forums, books, wikis, education, reference",
        "patterns": [
            r"4pda\.", r"4pna\.com$",
            r"ficbook\.net$", r"archiveofourown",
            r"babook\.org$", r"smashwords", r"abook-club",
            r"lolz\.guru$", r"forum\.ru-board", r"ru-board\.com$",
            r"skladchik", r"skladchina", r"sklatchiki",
            r"znanija\.com$",
            r"mrakopedia", r"wikidot", r"wikiart",
            r"fextralife", r"wiki\.fextralife",
            r"ldoceonline", r"spreadthesign",
            r"statology", r"lifehacker",
            r"aplawrence", r"middlewareinventory",
            r"htmhell", r"devops\.com$",
            r"pcmag\.com$", r"pcgamesn", r"extremetech",
            r"mashable\.com$", r"ign\.com$",
            r"vndb\.org$", r"w\.atwiki",
            r"rentry\.", r"pb\.wtf$",
            r"prnt\.sc$", r"piccy\.info$", r"fastpic\.org$",
            r"remove\.bg$", r"unscreen\.com$", r"watermarkremover",
            r"designify\.com$",
            r"webtoons\.com$", r"bato\.to$",
            r"pixiv\.net$", r"wixmp\.com$", r"deviantart",
            r"alphacoders\.com$",
            r"quiz\.directory$",
        ],
    },
    "tools-services": {
        "description": "Online tools, SIM services, file hosting, misc services",
        "patterns": [
            r"2ip\.ru$", r"addr\.tools$",
            r"5sim\.net$", r"onlinesim",
            r"gofile\.io$", r"fex\.net$", r"ufile\.io$", r"vipdrive",
            r"archive\.ph$",
            r"adguard", r"brave\.com$", r"ai-chat\.bsg\.brave",
            r"cursor\.sh$", r"authenticator\.cursor",
            r"ai\.com$",  # fallback if not caught by AI
            r"macpaw\.com$", r"macvendors",
            r"screamingfrog", r"serpstat",
            r"interactivebrokers",
            r"refinitiv\.com$",
            r"squareup\.com$", r"onfastspring",
            r"clipopus", r"clip\.opus",
            r"cvedetails\.com$", r"opensanctions",
            r"saverudata",
            r"privatekeys\.pw$",
            r"searchfloor",
            r"sysdig\.com$",
            r"nitropdf", r"gonitro",
            r"remna\.st$", r"render-state",
        ],
    },
    "hardware-electronics": {
        "description": "Hardware vendors, electronics distributors",
        "patterns": [
            r"digikey\.com$", r"mouser\.", r"newark\.com$", r"element14",
            r"pcbway", r"corsair\.com$", r"www3\.corsair",
            r"huawei\.com$",
            r"quietpc", r"squietpc", r"shinyhardware",
            r"btod\.com$",
            r"cpu-monkey", r"gpu-monkey",
            r"schaeffler", r"zf\.com$",
            r"plugshare\.com$",
            r"vectorworks\.net$",
        ],
    },
    "ua-media": {
        "description": "Ukrainian media, regional news",
        "patterns": [
            r"bihus\.info$", r"blackseanews",
            r"7dniv", r"atn\.ua$",
            r"liveuamap", r"deepstatemap",
            r"ill\.in\.ua", r"csskor", r"jskor", r"kor\.ill", r"ui\.ill",
            r"svidomi", r"svoi\.kr\.ua",
            r"merezha\.co$", r"neformat\.com\.ua$",
            r"patriot\.dp\.ua$", r"portal\.lviv",
            r"hyperhost\.ua$", r"weblance\.com\.ua$",
            r"ukrtelcdn",
            r"opposition-news",
            r"zerkalo\.io$",
            r"euroradio\.fm$", r"expres\.online$",
        ],
    },
    "media-db": {
        "description": "Media databases (TMDB, IMDB, etc.)",
        "patterns": [
            r"tmdb", r"themoviedb", r"image\.tmdb",
            r"theaudiodb",
            r"api\.themoviedb",
        ],
    },
    "misc": {
        "description": "Miscellaneous uncategorized",
        "patterns": [
            r"a-msedge", r"ggpht\.com$",
            r"cdn\.web-platform", r"web-platform\.io$",
            r"tdesktop\.com$",
            r"site\.com$", r"sky\.com$", r"skycdp",
            r"digitalcontent\.sky$",
            r"cnd2exp", r"zannn\.top$",
            r"czx\.to$", r"plab\.site$",
            r"underver\.se$",
            r"windows10spotlight",
            r"wheather\.com$",
            r"att\.com$",
            r"geni\.us$", r"genius\.com$",
            r"riotpixels", r"metal-archives",
            r"trueblackmetalradio",
            r"more\.fm$", r"uaudio\.com$", r"zedge\.net$",
            r"itninja", r"sdxcentral",
            r"broncosportforum",
            r"cats\.com$", r"carrefouruae",
            r"zetalliance",
            r"visualcapitalist",
            r"wk\.cz$", r"eggertspiele",
            r"alberta\.ca$", r"nippon\.com$",
            r"pap\.pl$", r"monster\.ie$",
            r"ef\.com$", r"ef\.edu$",
            r"edu-cisco",
            r"amdm\.ru$", r"php\.su$",
            r"mbed\.com$",
            r"kara\.su$",
            r"halooglasi",
            r"paraplan\.net$",
            r"buanzo\.org$", r"buckaroo\.nl$",
            r"roar-review", r"disctech",
            r"skiff\.com$",
            r"rus-media", r"rus\.ec$", r"rus\.jauns", r"jauns\.lv$",
            r"sakhalin\.info$",
            r"thebarentsobserver",
            r"t-invariant",
            r"voanews", r"vice\.com$",
            r"appstorrent", r"fls\.guru$",
            r"mdza\.io$", r"fork\.pet$",
            r"bitlaunch", r"bitru\.org$",
            r"booth\.pm$", r"booth\.pximg",
            r"smartbear", r"smartdeploy",
            r"smassets", r"soapui",
            r"platform\.activestate",
            r"tik-tokapi",
            r"telemetr\.io$",
            r"terrasoft",
            r"vrv\.co$",
            r"weebly\.com$",
            r"zerolab\.net$",
            r"dnsleaktest",  # should be in vpn-privacy
            r"iedb\.org$",
            r"healthline",
            r"data-cdn\.mbamupdates",
            r"aqicn\.org$",
            r"lolz\.guru$",
            r"ocstore\.com$", r"oculus\.com$",
            r"nyaa\.si$",
            r"cobalt", r"kemono", r"coomer",
        ],
    },
}

def load_domains(path: str) -> list[str]:
    domains = []
    with open(path) as f:
        for line in f:
            line = line.strip()
            if line and not line.startswith("#"):
                domains.append(line)
    return domains


def categorize(domains: list[str]) -> dict[str, list[str]]:
    result = defaultdict(list)
    uncategorized = []

    for domain in domains:
        matched = False
        for cat, info in CATEGORIES.items():
            for pattern in info["patterns"]:
                if re.search(pattern, domain):
                    result[cat].append(domain)
                    matched = True
                    break
            if matched:
                break
        if not matched:
            uncategorized.append(domain)

    result["other"] = uncategorized
    return dict(result)


def main():
    script_dir = Path(__file__).parent
    domains_dir = script_dir.parent / "domains"
    categories_dir = domains_dir / "categories"
    categories_dir.mkdir(exist_ok=True)

    domains = load_domains(domains_dir / "kvas_list_03_04_26.txt")
    print(f"Total domains: {len(domains)}")

    categorized = categorize(domains)

    for cat, cat_domains in sorted(categorized.items()):
        desc = CATEGORIES.get(cat, {}).get("description", "Uncategorized domains")
        outfile = categories_dir / f"{cat}.txt"
        with open(outfile, "w") as f:
            f.write(f"# {desc}\n")
            for d in sorted(set(cat_domains)):
                f.write(f"{d}\n")
        print(f"  {cat}: {len(cat_domains)} domains -> {outfile.name}")


if __name__ == "__main__":
    main()
